name: Generate GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *" # Every day at midnight UTC
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: AkhilRaawat
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata

          # Plugins
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_limit: 8

          plugin_stars: yes
          plugin_stars_limit: 4
